# Data

Los objetivos de este fichero son:
- Leer los datos proporcionados por Cajamar
- Analizar los datos brevemente
- Guardar los datos en formato HDF

Los aprendizajes y resultados obtenidos de este notebook:
- Leer datos y guardarlos en un formato mas conveniente
- Los valores nulos representan una cantidad mínima de observaciones train set = 0.0005% y test set = 0.0097%. Estos valores se encuentran en las variables MAXBUILDINGFLOOR y CADASTRALQUALITYID, si una de ellas es nula la otra también. Ambas provienen de los datos catastrales del gobierno. Estos valores pertenecen mayoritariamente a la clase AGRICULTURA, sobre esta es la que menos observaciones tenemos, aun así el porcentaje sobre esto sigue siendo ínfimo.
- Num. observaciones train = 103230 y test = 5618, 55 variables + Y.
- Las clases de Y están muy desbalanceadas.

### Imports

In [1]:
import pandas as pd

### Define variables

In [2]:
train_path = "../../Data/raw/Modelar_UH2020.csv"
test_path = "../../Data/raw/Estimar_UH2020.csv"
store_path_hdf5 = "../../Data/raw_hdf5/data.csv"
store_path_csv_X_train = "../../Data/raw_csv/X_train.csv"
store_path_csv_Y_train = "../../Data/raw_csv/Y_train.csv"
store_path_csv_X_test = "../../Data/raw_csv/Y_test.csv"

### Read RAW txt

In [3]:
def readRAW():
    XY_train = pd.read_csv(train_path, sep="|", header=0)
    X_test = pd.read_csv(test_path, sep="|", header=0)
    return XY_train, X_test

### Store DF

In [4]:
def storeCSV(X_train,Y_train, X_test):
    X_train.to_csv(store_path_csv_X_train,index = False, header=True)
    Y_train.to_csv(store_path_csv_Y_train,index = False, header=True)
    X_test.to_csv(store_path_csv_X_test,index = False, header=True)

In [5]:
def storeHDF5(X_train, Y_train, X_test):
    X_train.to_hdf(store_path_hdf5,index = False, header=True,key='X_train',format='t')
    Y_train.to_hdf(store_path_hdf5,index = False, header=True,key='Y_train',format='t')
    X_test.to_hdf(store_path_hdf5,index = False, header=True,key='X_test',format='t')

### Read data

In [6]:
XY_train, X_test = readRAW()

In [18]:
XY_train.dtypes

ID                    category
X                        int64
Y                        int64
Q_R_4_0_0              float64
Q_R_4_0_1              float64
Q_R_4_0_2              float64
Q_R_4_0_3              float64
Q_R_4_0_4              float64
Q_R_4_0_5              float64
Q_R_4_0_6              float64
Q_R_4_0_7              float64
Q_R_4_0_8              float64
Q_R_4_0_9              float64
Q_R_4_1_0              float64
Q_G_3_0_0              float64
Q_G_3_0_1              float64
Q_G_3_0_2              float64
Q_G_3_0_3              float64
Q_G_3_0_4              float64
Q_G_3_0_5              float64
Q_G_3_0_6              float64
Q_G_3_0_7              float64
Q_G_3_0_8              float64
Q_G_3_0_9              float64
Q_G_3_1_0              float64
Q_B_2_0_0              float64
Q_B_2_0_1              float64
Q_B_2_0_2              float64
Q_B_2_0_3              float64
Q_B_2_0_4              float64
Q_B_2_0_5              float64
Q_B_2_0_6              float64
Q_B_2_0_7              float64
Q_B_2_0_8              float64
Q_B_2_0_9              float64
Q_B_2_1_0              float64
Q_NIR_8_0_0            float64
Q_NIR_8_0_1            float64
Q_NIR_8_0_2            float64
Q_NIR_8_0_3            float64
Q_NIR_8_0_4            float64
Q_NIR_8_0_5            float64
Q_NIR_8_0_6            float64
Q_NIR_8_0_7            float64
Q_NIR_8_0_8            float64
Q_NIR_8_0_9            float64
Q_NIR_8_1_0            float64
AREA                   float64
GEOM_R1                float64
GEOM_R2                float64
GEOM_R3                float64
GEOM_R4                float64
CONTRUCTIONYEAR          int64
MAXBUILDINGFLOOR       float64
CADASTRALQUALITYID    category
CLASE                 category
dtype: object

In [8]:
#Convertimos a variables categoricas
XY_train['CLASE'] = pd.Categorical(XY_train.CLASE)
XY_train['CADASTRALQUALITYID'] = pd.Categorical(XY_train.CADASTRALQUALITYID)
"""
En esta variable existe una relación entre las distintas clases, no se cual ya que esta información
no se expresa en la faq de los datos del catastro, pero voy a contactar para preguntar.
Punto 17: http://www.catastro.minhap.es/documentos/preguntas_frecuentes_formato_CAT.pdf
"""
XY_train['ID'] = pd.Categorical(XY_train.ID)
#En principio ID no se usará pero la quiero estudiar por posible data leakage
XY_train.dtypes

ID                    category
X                        int64
Y                        int64
Q_R_4_0_0              float64
Q_R_4_0_1              float64
Q_R_4_0_2              float64
Q_R_4_0_3              float64
Q_R_4_0_4              float64
Q_R_4_0_5              float64
Q_R_4_0_6              float64
Q_R_4_0_7              float64
Q_R_4_0_8              float64
Q_R_4_0_9              float64
Q_R_4_1_0              float64
Q_G_3_0_0              float64
Q_G_3_0_1              float64
Q_G_3_0_2              float64
Q_G_3_0_3              float64
Q_G_3_0_4              float64
Q_G_3_0_5              float64
Q_G_3_0_6              float64
Q_G_3_0_7              float64
Q_G_3_0_8              float64
Q_G_3_0_9              float64
Q_G_3_1_0              float64
Q_B_2_0_0              float64
Q_B_2_0_1              float64
Q_B_2_0_2              float64
Q_B_2_0_3              float64
Q_B_2_0_4              float64
Q_B_2_0_5              float64
Q_B_2_0_6              float64
Q_B_2_0_7              float64
Q_B_2_0_8              float64
Q_B_2_0_9              float64
Q_B_2_1_0              float64
Q_NIR_8_0_0            float64
Q_NIR_8_0_1            float64
Q_NIR_8_0_2            float64
Q_NIR_8_0_3            float64
Q_NIR_8_0_4            float64
Q_NIR_8_0_5            float64
Q_NIR_8_0_6            float64
Q_NIR_8_0_7            float64
Q_NIR_8_0_8            float64
Q_NIR_8_0_9            float64
Q_NIR_8_1_0            float64
AREA                   float64
GEOM_R1                float64
GEOM_R2                float64
GEOM_R3                float64
GEOM_R4                float64
CONTRUCTIONYEAR          int64
MAXBUILDINGFLOOR       float64
CADASTRALQUALITYID    category
CLASE                 category
dtype: object

In [9]:
Y_train = XY_train['CLASE']
X_train = XY_train.drop(columns='CLASE',inplace=False)

### Analyze data

#### Train data

In [10]:
print('X INPUT')
print('Número de observaciones = ', X_train.shape[0])
print('Número de variables = ', X_train.shape[1])
print('Count total Nulls = ',X_train.isnull().sum().sum())
print('% Observaciones con Nulls = \n', sum(map(any, X_train.isnull()))/X_train.shape[0])
print('Count Nulls by columns = \n',X_train.isnull().sum())

X INPUT
Número de observaciones =  103230
Número de variables =  55
Count total Nulls =  40
% Observaciones con Nulls =
 0.0005327908553715005
Count Nulls by columns =
 ID                     0
X                      0
Y                      0
Q_R_4_0_0              0
Q_R_4_0_1              0
Q_R_4_0_2              0
Q_R_4_0_3              0
Q_R_4_0_4              0
Q_R_4_0_5              0
Q_R_4_0_6              0
Q_R_4_0_7              0
Q_R_4_0_8              0
Q_R_4_0_9              0
Q_R_4_1_0              0
Q_G_3_0_0              0
Q_G_3_0_1              0
Q_G_3_0_2              0
Q_G_3_0_3              0
Q_G_3_0_4              0
Q_G_3_0_5              0
Q_G_3_0_6              0
Q_G_3_0_7              0
Q_G_3_0_8              0
Q_G_3_0_9              0
Q_G_3_1_0              0
Q_B_2_0_0              0
Q_B_2_0_1              0
Q_B_2_0_2              0
Q_B_2_0_3              0
Q_B_2_0_4              0
Q_B_2_0_5              0
Q_B_2_0_6              0
Q_B_2_0_7              0
Q_B_2_0_8              0
Q_B_2_0_9              0
Q_B_2_1_0              0
Q_NIR_8_0_0            0
Q_NIR_8_0_1            0
Q_NIR_8_0_2            0
Q_NIR_8_0_3            0
Q_NIR_8_0_4            0
Q_NIR_8_0_5            0
Q_NIR_8_0_6            0
Q_NIR_8_0_7            0
Q_NIR_8_0_8            0
Q_NIR_8_0_9            0
Q_NIR_8_1_0            0
AREA                   0
GEOM_R1                0
GEOM_R2                0
GEOM_R3                0
GEOM_R4                0
CONTRUCTIONYEAR        0
MAXBUILDINGFLOOR      20
CADASTRALQUALITYID    20
dtype: int64

Solo las variables MAXBUILDINGFLOOR y CADASTRALQUALITYID contienen valores nulos.

In [11]:
# Output variable
print('\nY OUTPUT')
print('Count Nulls = ',Y_train.isnull().sum().sum())
Y_classes = Y_train.value_counts()
Y_classes_rev = Y_classes/Y_train.shape[0]
print('VALORES Y:\n',Y_classes,'\n', Y_classes_rev)

Y OUTPUT
Count Nulls =  0
VALORES Y:
 RESIDENTIAL    90173
INDUSTRIAL      4490
PUBLIC          2976
RETAIL          2093
OFFICE          1828
OTHER           1332
AGRICULTURE      338
Name: CLASE, dtype: int64
 RESIDENTIAL    0.873515
INDUSTRIAL     0.043495
PUBLIC         0.028829
RETAIL         0.020275
OFFICE         0.017708
OTHER          0.012903
AGRICULTURE    0.003274
Name: CLASE, dtype: float64

Las clases de salida están muy desbalanceadas

In [12]:
XY_train.head().T

,0,1,2,3,4
ID,35984B9C3E7CD9A1,F9D04BF6D037F8FB,B89D5711AFF8C423,1C3478AC1522E7E4,4D12AA5009064345
X,2207357872,2189757160,2240147335,2227146459,2212350459
Y,165920300,165463267,165690752,165934099,165681791
Q_R_4_0_0,0,5.87961e-05,0,0,0
Q_R_4_0_1,443.001,443.899,353.502,268.001,318.998
Q_R_4_0_2,616.002,627.999,523.004,377,492.004
Q_R_4_0_3,746.998,770.002,644.002,478.004,633
Q_R_4_0_4,872.996,905,760.997,575.001,757.002
Q_R_4_0_5,1009,1033,877,683.998,883
Q_R_4_0_6,1159,1165,1007,809.006,1019.01
Q_R_4_0_7,1342,1316,1169,955.003,1175.99
Q_R_4_0_8,1572,1505.99,1375.01,1137,1401
Q_R_4_0_9,1943.69,1804.99,1719,1448,1756.99
Q_R_4_1_0,6512.79,6269.94,5010.77,5465.43,7376.53
Q_G_3_0_0,1.28336e-10,1.35252e-11,0,6.34159e-06,0
Q_G_3_0_1,428.996,433.998,379.002,310.999,284.001
Q_G_3_0_2,574.001,565,507.004,405.999,421.002
Q_G_3_0_3,676.003,662.997,600.001,485.001,526.004
Q_G_3_0_4,778.004,746.001,684,558.998,618.999
Q_G_3_0_5,880.999,828.998,768.998,641.001,705.999
Q_G_3_0_6,997,912,867.002,731.994,801.005
Q_G_3_0_7,1130,1012,992.992,838.004,912.999
Q_G_3_0_8,1312,1142.2,1166,974.797,1070
Q_G_3_0_9,1627,1384.99,1443,1218,1348.5
Q_G_3_1_0,8627.1,5357.79,5240.23,5343.17,7460.39
Q_B_2_0_0,155.004,120,83.0004,0.00144985,193.001
Q_B_2_0_1,402,419,363,256.999,431.505
Q_B_2_0_2,459,473,429.003,296,463
Q_B_2_0_3,510,510,473,329,492
Q_B_2_0_4,568,542,510,366,519
Q_B_2_0_5,632.001,572,549,411.001,547
Q_B_2_0_6,681.001,603,591,457,579
Q_B_2_0_7,726.109,636,636,506,618
Q_B_2_0_8,791,673,693,566,663
Q_B_2_0_9,903,745,796.499,664,750
Q_B_2_1_0,1980.17,3647.2,1947.74,1424.4,1940.4
Q_NIR_8_0_0,1.34289e-05,2.96746e-05,5.15823e-06,0.00228463,0
Q_NIR_8_0_1,892.016,846.003,807.001,1200.99,529.004
Q_NIR_8_0_2,1244.01,1139.01,1124,1476,790.997
Q_NIR_8_0_3,1498,1363.99,1365.01,1678.01,999.002
Q_NIR_8_0_4,1731.2,1558,1571,1848,1184
Q_NIR_8_0_5,1944,1749.99,1768.99,2022.99,1355.99
Q_NIR_8_0_6,2161,1956,1978.99,2211.99,1536
Q_NIR_8_0_7,2411,2194,2229,2433,1725.5
Q_NIR_8_0_8,2720,2507,2562,2741,1954.99
Q_NIR_8_0_9,3180,3012.99,3088,3349.99,2315.99
Q_NIR_8_1_0,10951.9,7048.37,7013.07,6216.88,7092.77
AREA,144.427,38.3425,108.794,155.224,1789.87
GEOM_R1,0.557237,0.709884,0.517702,0.450871,0.458819
GEOM_R2,0.0672495,0.125156,0.0582683,0.0535906,0.0128581
GEOM_R3,0.0573723,0.147929,0.081666,0.0542005,0.0199362
GEOM_R4,0.853127,1.18195,1.40155,1.01138,1.55048
CONTRUCTIONYEAR,2002,1949,1986,1999,1966
MAXBUILDINGFLOOR,0,1,1,1,8
CADASTRALQUALITYID,2,8,5,2,6
CLASE,RESIDENTIAL,RESIDENTIAL,RESIDENTIAL,RESIDENTIAL,RESIDENTIAL

In [13]:
XY_train[XY_train.isna().any(axis=1)]

,ID,X,Y,Q_R_4_0_0,Q_R_4_0_1,Q_R_4_0_2,Q_R_4_0_3,Q_R_4_0_4,Q_R_4_0_5,Q_R_4_0_6,...,Q_NIR_8_1_0,AREA,GEOM_R1,GEOM_R2,GEOM_R3,GEOM_R4,CONTRUCTIONYEAR,MAXBUILDINGFLOOR,CADASTRALQUALITYID,CLASE
9864,B7DE3FE20084F9FA,2254413625,165244276,0.000597,592.998193,742.001184,855.996881,976.798755,1106.998474,1238.995532,...,6763.517046,2120.276750,0.465508,0.015959,0.013757,0.862017,1975,NaN,NaN,INDUSTRIAL
10145,5D08956CDC0B7C37,2250193143,165232359,0.000000,648.000018,788.999866,894.999255,987.001318,1079.999817,1184.999121,...,6084.405066,1999.778850,0.531552,0.016810,0.015813,0.940702,1975,NaN,NaN,AGRICULTURE
12273,20D3200047F4D73A,2254610358,165241603,0.000597,592.998193,742.001184,855.996881,976.798755,1106.998474,1238.995532,...,6763.517046,723.268350,0.563042,0.036284,0.021455,0.591289,1975,NaN,NaN,AGRICULTURE
13089,82489ECC7BDFB0B0,2250087048,165252257,0.000000,648.000018,788.999866,894.999255,987.001318,1079.999817,1184.999121,...,6084.405066,1829.160728,0.153173,0.009619,0.008705,0.905010,1975,NaN,NaN,RETAIL
16330,6447D96932B64C3F,2250800402,165234583,0.000000,648.000018,788.999866,894.999255,987.001318,1079.999817,1184.999121,...,6084.405066,249.497550,0.361907,0.040209,0.036075,0.897186,1975,NaN,NaN,AGRICULTURE
23184,8BF6E2CB5B152739,2248534716,165225185,0.000000,648.000018,788.999866,894.999255,987.001318,1079.999817,1184.999121,...,6084.405066,159.968400,0.294582,0.042373,0.043459,1.025641,1975,NaN,NaN,AGRICULTURE
34988,621448B2B12E3B3E,2233865202,165097257,0.000009,609.998492,778.999695,889.001544,976.000098,1068.000366,1169.998853,...,5208.317414,710.658165,0.115690,0.014473,0.011248,0.777191,1950,NaN,NaN,AGRICULTURE
38537,042ABAFAE9B5BDB9,2246045656,165214428,0.000000,648.000018,788.999866,894.999255,987.001318,1079.999817,1184.999121,...,6084.405066,4112.808185,0.028464,0.003521,0.001966,0.558325,1966,NaN,NaN,INDUSTRIAL
43448,55B7201B5219C83B,2260254994,165132637,0.000004,437.000958,597.003247,711.998651,806.999329,910.999084,1039.000195,...,5922.090811,47.266733,0.043968,0.031348,0.029674,0.946588,1982,NaN,NaN,AGRICULTURE
48059,51DCB5C9945A826E,2239496952,165148413,0.000006,493.999994,610.000061,687.999243,754.999768,824.999542,912.000513,...,5270.232234,88.353700,0.469356,0.068634,0.077399,1.127709,1957,NaN,NaN,AGRICULTURE
55054,D9A6B8B330C11143,2253924221,165223854,0.000597,592.998193,742.001184,855.996881,976.798755,1106.998474,1238.995532,...,6763.517046,8997.809000,0.035354,0.002757,0.001425,0.517025,1975,NaN,NaN,AGRICULTURE
57998,41FB599E9B4816A8,2246888671,165177534,0.000760,641.000610,764.999939,875.999817,990.000061,1116.992004,1286.000854,...,7712.102151,958.381450,0.218652,0.008562,0.026645,3.111910,1966,NaN,NaN,AGRICULTURE
61724,C339404268E66A71,2240645160,165170912,1.016050,656.998816,753.997913,834.000061,909.000635,985.000031,1068.000659,...,6227.741406,1566.221950,0.026735,0.003917,0.004358,1.112656,1966,NaN,NaN,AGRICULTURE
67773,353645ED2FA18A,2233716870,165108956,0.000009,609.998492,778.999695,889.001544,976.000098,1068.000366,1169.998853,...,5208.317414,103410.248537,0.487248,0.002164,0.002177,1.006096,1950,NaN,NaN,AGRICULTURE
69253,B4A58FDBD97DA74B,2255636575,165095665,0.000004,437.000958,597.003247,711.998651,806.999329,910.999084,1039.000195,...,5922.090811,1083.745180,0.152886,0.008717,0.016184,1.856596,1975,NaN,NaN,AGRICULTURE
71932,99C000CA552F2F1A,2246109269,165175274,0.000760,641.000610,764.999939,875.999817,990.000061,1116.992004,1286.000854,...,7712.102151,719.815650,0.299387,0.015946,0.026082,1.635629,1966,NaN,NaN,AGRICULTURE
76837,2CC4B745CE79E7C7,2238737866,165233240,0.003241,732.000824,846.999390,929.000122,1006.999573,1091.998230,1190.000000,...,6525.757126,265.335000,0.453691,0.046970,0.036403,0.775027,1966,NaN,NaN,INDUSTRIAL
78351,D715EFB7AB240B96,2257571528,165116729,0.000004,437.000958,597.003247,711.998651,806.999329,910.999084,1039.000195,...,5922.090811,50.010750,0.532060,0.118624,0.089686,0.756054,1982,NaN,NaN,AGRICULTURE
78891,BE7A8EF34949F941,2256124126,165224223,0.000597,592.998193,742.001184,855.996881,976.798755,1106.998474,1238.995532,...,6763.517046,32376.156200,0.127731,0.002600,0.001517,0.583445,1975,NaN,NaN,INDUSTRIAL
102247,3E0790BED7BFB548,2253919302,165257556,0.000597,592.998193,742.001184,855.996881,976.798755,1106.998474,1238.995532,...,6763.517046,224.965000,0.500545,0.047170,0.047170,1.000000,1975,NaN,NaN,AGRICULTURE

Se observa como si una de las dos variables es nula la otra también, 
por lo que aunque el número de valores nulos en el dataframe es de 40,
el número de observaciones con algún valor nulo es de 20.

La mayoría de estas observaciones pertenecen a la Clase AGRICULTURA,
la cual es de la que menos observaciones se tiene.

In [14]:
X_train['CADASTRALQUALITYID'].value_counts(dropna=False)

4      24621
6      24528
5      19473
7      13799
3      10209
8       5547
2       2980
9       1105
1        652
C        216
B         43
A         37
NaN       20
Name: CADASTRALQUALITYID, dtype: int64

In [15]:
X_train['MAXBUILDINGFLOOR'].value_counts(dropna=False)

1.0     34548
5.0     16296
4.0     14683
3.0      8787
6.0      7130
7.0      5341
2.0      3923
8.0      3586
0.0      2628
9.0      1787
10.0     1370
12.0      795
11.0      706
13.0      635
14.0      474
15.0      175
16.0      128
17.0       86
21.0       49
22.0       21
18.0       20
NaN        20
25.0       16
23.0       16
19.0        6
24.0        3
20.0        1
Name: MAXBUILDINGFLOOR, dtype: int64

#### Test Data

In [16]:
print('X INPUT')
print('Número de observaciones = ', X_test.shape[0])
print('Número de variables = ', X_test.shape[1])
print('Count total Nulls = ',X_test.isnull().sum().sum())
print('% Observaciones con Nulls = \n', sum(map(any, X_test.isnull()))/X_test.shape[0])
print('Count Nulls by columns = ',X_test.isnull().sum())

X INPUT
Número de observaciones =  5618
Número de variables =  55
Count total Nulls =  14
% Observaciones con Nulls =
 0.009789960840156639
Count Nulls by columns =  ID                    0
X                     0
Y                     0
Q_R_4_0_0             0
Q_R_4_0_1             0
Q_R_4_0_2             0
Q_R_4_0_3             0
Q_R_4_0_4             0
Q_R_4_0_5             0
Q_R_4_0_6             0
Q_R_4_0_7             0
Q_R_4_0_8             0
Q_R_4_0_9             0
Q_R_4_1_0             0
Q_G_3_0_0             0
Q_G_3_0_1             0
Q_G_3_0_2             0
Q_G_3_0_3             0
Q_G_3_0_4             0
Q_G_3_0_5             0
Q_G_3_0_6             0
Q_G_3_0_7             0
Q_G_3_0_8             0
Q_G_3_0_9             0
Q_G_3_1_0             0
Q_B_2_0_0             0
Q_B_2_0_1             0
Q_B_2_0_2             0
Q_B_2_0_3             0
Q_B_2_0_4             0
Q_B_2_0_5             0
Q_B_2_0_6             0
Q_B_2_0_7             0
Q_B_2_0_8             0
Q_B_2_0_9             0
Q_B_2_1_0             0
Q_NIR_8_0_0           0
Q_NIR_8_0_1           0
Q_NIR_8_0_2           0
Q_NIR_8_0_3           0
Q_NIR_8_0_4           0
Q_NIR_8_0_5           0
Q_NIR_8_0_6           0
Q_NIR_8_0_7           0
Q_NIR_8_0_8           0
Q_NIR_8_0_9           0
Q_NIR_8_1_0           0
AREA                  0
GEOM_R1               0
GEOM_R2               0
GEOM_R3               0
GEOM_R4               0
CONTRUCTIONYEAR       0
MAXBUILDINGFLOOR      7
CADASTRALQUALITYID    7
dtype: int64

Aunque la cantidad de valores nulos en el train set y en el test set sea ínfima, decido imputarlos en un próximo notebook

### Store data

In [17]:
storeHDF5(X_train,Y_train,X_test)
storeCSV(X_train,Y_train,X_test)